# Generated by Django 5.0.6 on 2024-07-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('taluka', models.CharField(max_length=30)),
                ('dist', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('addharno', models.IntegerField()),
                ('voterid', models.IntegerField()),
                ('mobno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='voterid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voterregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('taluka', models.CharField(max_length=30)),
                ('dist', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('addharno', models.IntegerField()),
                ('voterid', models.IntegerField()),
                ('mobno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('vote', models.IntegerField(default=0, editable=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='Election_System.newregistration')),
            ],
        ),
        migrations.CreateModel(
            name='voted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('voteusername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteusername', to='Election_System.post')),
            ],
        ),
    ]
