# Generated by Django 5.0.6 on 2024-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregistration',
            name='partyimg',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='voterregistration',
            name='partynm',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=30),
        ),
    ]
