# Generated by Django 5.0.6 on 2024-07-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election_System', '0002_voterregistration_partyimg_voterregistration_partynm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completedvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterid', models.IntegerField()),
                ('fullname', models.CharField(max_length=200)),
                ('vote', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.RemoveField(
            model_name='voted',
            name='voteusername',
        ),
        migrations.DeleteModel(
            name='voterid',
        ),
        migrations.RemoveField(
            model_name='newregistration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='voterregistration',
            name='password',
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='voterregistration',
            name='partyimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voterregistration',
            name='partynm',
            field=models.CharField(blank=True, choices=[('BJP', 'Bharatiya Janata Party'), ('Congress', 'Congress'), ('Shiv Sena', 'Shiv Sena'), ('Shiv Sena Thackeray', 'Shiv Sena Uddhav Balasaheb Thackeray'), ('Rashtrawadi Congress', 'Rashtrawadi Congress'), ('Manase', 'Maharashtra Navnirman Sena')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voterregistration',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='voted',
        ),
    ]
