# Generated by Django 5.0.6 on 2024-07-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election_System', '0004_post_voted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='voted',
        ),
    ]
