# Generated by Django 5.0.6 on 2024-07-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election_System', '0005_delete_post_delete_voted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedvote',
            old_name='fullname',
            new_name='fn',
        ),
        migrations.RenameField(
            model_name='completedvote',
            old_name='voterid',
            new_name='vid',
        ),
    ]
