# Generated by Django 5.0.6 on 2024-07-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election_System', '0006_rename_fullname_completedvote_fn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedvote',
            old_name='fn',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='completedvote',
            old_name='vid',
            new_name='voterid',
        ),
    ]
